### ISSUE TITLE
Issue with the -fix Parameter Adding Version Number for 1.12.2 Maps, but the Game Still Fails to Load Them

### ISSUE THREAD

**Issue by bierdosenhalter** [nothub/mapart#2]
When using the -fix parameter with my maps for version 1.12.2, the tool appends an version number (1343) to the map file. Although the dimension changes correctly, the game (1.20.4) fails to load the maps with this version number.

After manually changing the version number to 3700, the maps load correctly without any issues.

**Comment by nothub** [comment]
Fixed with 33eca5ffdffd1f05014e8138661f2fdfa771fa48

Thanks for the report!
